FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase

    Velocity_LowerBody:
      id: 4
      type: RLBase

    Mimic_TaiChi:
      id: 5
      type: Mimic
    
    Mimic_PickUpBox:
      id: 6
      type: Mimic

    Mimic_Lafan1_Dance1_Subject2:
      id: 7
      type: Mimic

    Mimic_Squat:
      id: 8
      type: Mimic

    Mimic_Move_Arms:
      id: 9
      type: Mimic

    HipHop:
      id: 10
      type: Mimic

    TaeKwonDo:
      id: 11
      type: Mimic

  Passive:
    transitions: 
      FixStand: "1" #  or "1" in the keyboard
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]


  FixStand:
    transitions: 
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    kp: [
      100,100,100,150,40,40,
      100,100,100,150,40,40,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 2]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0.35, 0.18,0,0.87,0,0,0,
        0.35,-0.18,0,0.87,0,0,0
      ]
    ]


  Velocity:
    transitions: 
      Passive: "0" #  or "0" in the keyboard
      FixStand: "1" #  or "1" in the keyboard
      Mimic_TaiChi: "3" #  or "3" in the keyboard
      Mimic_PickUpBox: "4" # "4" in the keyboard
      Mimic_Lafan1_Dance1_Subject2: "5" # "5" in the keyboard
      Mimic_Squat: "6" # "6" in the keyboard
      Mimic_Move_Arms: "7" # "7" in the keyboard
      HipHop: "8" # "8" in the keyboard
      TaeKwonDo: "9" # "9" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard
      
    policy_dir: config/policy/velocity/v0

  Velocity_LowerBody:
    transitions: 
      Passive: "0" #  or "0" in the keyboard
      FixStand: "1" #  or "1" in the keyboard
      Mimic_TaiChi: "3" #  or "3" in the keyboard
      Mimic_PickUpBox: "4" # "4" in the keyboard
      Mimic_Lafan1_Dance1_Subject2: "5" # "5" in the keyboard
      Mimic_Squat: "6" # "6" in the keyboard
      Mimic_Move_Arms: "7" # "7" in the keyboard
      HipHop: "8" # "8" in the keyboard
      TaeKwonDo: "9" # "9" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      
    policy_dir: config/policy/velocity/lower_body

    upper_body_kp: [
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    upper_body_kd: [
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    upper_body_qs: [
      0.35, 0.18,0,0.87,0,0,0,
      0.35,-0.18,0,0.87,0,0,0
    ]

  Mimic_TaiChi:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/taichi_v0/params/tai_chi.npz
    policy_dir: config/policy/mimic/taichi_v0/
    time_start: 0.0
    time_end: 1000.0

  Mimic_PickUpBox:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/pick_up_box/params/ACCAD_Female1General_c3d_A5_pick_up_box_stageii.npz
    policy_dir: config/policy/mimic/pick_up_box/
    time_start: 0.0
    time_end: 1000.0

  Mimic_Lafan1_Dance1_Subject2:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/lafan1_dance1_subject2/params/dance1_subject2.npz
    policy_dir: config/policy/mimic/lafan1_dance1_subject2/
    time_start: 0.0
    time_end: 1000.0

  Mimic_Squat:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/squat_gvhmr/params/squat_gvhmr.npz
    policy_dir: config/policy/mimic/squat_gvhmr/
    time_start: 0.0
    time_end: 1000.0

  Mimic_Move_Arms:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/move_arms_gvhmr/params/move_arms_gvhmr.npz
    policy_dir: config/policy/mimic/move_arms_gvhmr/
    time_start: 0.0
    time_end: 1000.0

  HipHop:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard

    motion_file: config/policy/mimic/hiphop/params/hiphop_gvhmr.npz
    policy_dir: config/policy/mimic/hiphop/
    time_start: 0.0
    time_end: 1000.0

  TaeKwonDo:
    transitions:
      Passive: "0" #  or "0" in the keyboard
      Velocity: "2" #  or "2" in the keyboard
      Velocity_LowerBody: "c" #  or "c" in the keyboard
    
    motion_file: config/policy/mimic/taekwondo/params/taekwondo_gvhmr.npz
    policy_dir: config/policy/mimic/taekwondo/
    time_start: 0.0
    time_end: 1000.0